version: '3'
services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    restart: always
